// <auto-generated />
using Euroskills2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euroskills2018.Migrations
{
    [DbContext(typeof(EuroskillsDbContext))]
    partial class EuroskillsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Euroskills2018.Models.OrszagModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("orszagNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Orszagok");
                });

            modelBuilder.Entity("Euroskills2018.Models.SzakmaModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("szakmaNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Szakmak");
                });

            modelBuilder.Entity("Euroskills2018.Models.VersenyzoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orszagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("pont")
                        .HasColumnType("INTEGER");

                    b.Property<string>("szakmaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("orszagId");

                    b.HasIndex("szakmaId");

                    b.ToTable("Versenyzok");
                });

            modelBuilder.Entity("Euroskills2018.Models.VersenyzoModel", b =>
                {
                    b.HasOne("Euroskills2018.Models.OrszagModel", "Orszag")
                        .WithMany("Versenyzok")
                        .HasForeignKey("orszagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Euroskills2018.Models.SzakmaModel", "Szakma")
                        .WithMany("Versenyzok")
                        .HasForeignKey("szakmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orszag");

                    b.Navigation("Szakma");
                });

            modelBuilder.Entity("Euroskills2018.Models.OrszagModel", b =>
                {
                    b.Navigation("Versenyzok");
                });

            modelBuilder.Entity("Euroskills2018.Models.SzakmaModel", b =>
                {
                    b.Navigation("Versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
